cancer_types:
  #- BRCA
  #- LGG
  #- GBM
  #- KIRC
  - CCRCC
  - HNSCC
  - PDA
  #- NSCLC

clinical_data:
  #NSCLC: "<path_to_NSCLC_clinical_data>"
  #BRCA: "<path_to_BRCA_clinical_data>"
  #LGG: "<path_to_LGG_clinical_data>"
  #GBM: "<path_to_GBM_clinical_data>"
  #KIRC: "<path_to_KIRC_clinical_data>"
  CCRCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/Clinical_data/combined_clinical/CCRCC_combined_clinical_data.csv"
  HNSCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/Clinical_data/combined_clinical/HNSCC_combined_clinical_data.csv"
  PDA: "/cluster/projects/bhklab/rawdata/Radiogenomics/Clinical_data/combined_clinical/PDA_combined_clinical_data.csv"

sample_ids:
  #NSCLC: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/NSCLC_patientids.txt"
  HNSCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/CPTAC_HNSCC_patientids.txt"
  PDA: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/CPTAC_PDA_patientids.txt"
  CCRCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/CPTAC_CCRCC_patientids.txt"
  #GBM: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/TCGA_GBM_patientids.txt"
  #BRCA: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/TCGA_BRCA_patientids.txt"
  #KIRC: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/TCGA_KIRC_patientids.txt"
  #LGG: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/TCGA_LGG_patientids.txt"
radiomics_file:
  #NSCLC: "<path_to_NSCLC_radiomics_features>"
  #BRCA: "<path_to_BRCA_radiomics_features>"
  #LGG: "<path_to_LGG_radiomics_features>"
  #GBM: "<path_to_GBM_radiomics_features>"
  #KIRC: "<path_to_KIRC_radiomics_features>"
  CCRCC: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/CCRCC/CCRCC_radiomics_features_filtered.csv"
  HNSCC: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/HNSCC/HNSCC_radiomics_features_filtered.csv"
  PDA: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/PDA/PDA_radiomics_features_filtered.csv"
genomics_file:
  HNSCC:
    HALLMARK: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/HNSCC/HNSCC_HALLMARK_features_filtered.csv"
    KEGG: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/HNSCC/HNSCC_KEGG_features_filtered.csv"
    REACTOME: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/HNSCC/HNSCC_REACTOME_features_filtered.csv"
    BIOCARTA: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/HNSCC/HNSCC_BIOCARTA_features_filtered.csv"
  #NSCLC:
    #Hallmark: "<path_to_NSCLC_hallmark_genomics_data>"
    #Kegg: "<path_to_NSCLC_kegg_genomics_data>"
    #Reactome: "<path_to_NSCLC_reactome_genomics_data>"
    #Biocarta: "<path_to_NSCLC_biocarta_genomics_data>"
  PDA:
    HALLMARK: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/PDA/PDA_HALLMARK_features_filtered.csv"
    KEGG: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/PDA/PDA_KEGG_features_filtered.csv"
    REACTOME: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/PDA/PDA_REACTOME_features_filtered.csv"
    BIOCARTA: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/PDA/PDA_BIOCARTA_features_filtered.csv"
  CCRCC:
    HALLMARK: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/CCRCC/CCRCC_HALLMARK_features_filtered.csv"
    KEGG: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/CCRCC/CCRCC_KEGG_features_filtered.csv"
    REACTOME: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/CCRCC/CCRCC_REACTOME_features_filtered.csv"
    BIOCARTA: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/CCRCC/CCRCC_BIOCARTA_features_filtered.csv"
  #GBM:
    #Hallmark: "<path_to_GBM_hallmark_genomics_data>"
    #Kegg: "<path_to_GBM_kegg_genomics_data>"
    #Reactome: "<path_to_GBM_reactome_genomics_data>"
    #Biocarta: "<path_to_GBM_biocarta_genomics_data>"
  #BRCA:
    #Hallmark: "<path_to_BRCA_hallmark_genomics_data>"
    #Kegg: "<path_to_BRCA_kegg_genomics_data>"
    #Reactome: "<path_to_BRCA_reactome_genomics_data>"
    #Biocarta: "<path_to_BRCA_biocarta_genomics_data>"
  #KIRC:
    #Hallmark: "<path_to_KIRC_hallmark_genomics_data>" 
    #Kegg: "<path_to_KIRC_kegg_genomics_data>"
    #Reactome: "<path_to_KIRC_reactome_genomics_data>"
    #Biocarta: "<path_to_KIRC_biocarta_genomics_data>"
  #LGG:
    #Hallmark: "<path_to_LGG_hallmark_genomics_data>"
    #Kegg: "<path_to_LGG_kegg_genomics_data>"
    #Reactome: "<path_to_LGG_reactome_genomics_data>"
    #Biocarta: "<path_to_LGG_biocarta_genomics_data>"  


output_dir: 
  #BRCA: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/BRCA/"
  #LGG: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/LGG/"
  #GBM: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/GBM/"
  #KIRC: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/KIRC/"
  CCRCC: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/CCRCC/"
  HNSCC: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/HNSCC/"
  PDA: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/PDA/"
