cancer_types:
  - BRCA
  - LGG
  - KIRC
  - CCRCC
  - HNSCC
  - PDA

clinical_data:
  BRCA: "/cluster/projects/bhklab/rawdata/Radiogenomics/Clinical_data/combined_clinical/BRCA_combined_clinical_data.csv"
  LGG: "/cluster/projects/bhklab/rawdata/Radiogenomics/Clinical_data/combined_clinical/LGG_combined_clinical_data.csv"
  KIRC: "/cluster/projects/bhklab/rawdata/Radiogenomics/Clinical_data/combined_clinical/KIRC_combined_clinical_data.csv"
  CCRCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/Clinical_data/combined_clinical/CCRCC_combined_clinical_data.csv"
  HNSCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/Clinical_data/combined_clinical/HNSCC_combined_clinical_data.csv"
  PDA: "/cluster/projects/bhklab/rawdata/Radiogenomics/Clinical_data/combined_clinical/PDA_combined_clinical_data.csv"
sample_ids:
  HNSCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/CPTAC_HNSCC_patientids.txt"
  PDA: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/CPTAC_PDA_patientids.txt"
  CCRCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/CPTAC_CCRCC_patientids.txt"
  BRCA: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/TCGA_BRCA_patientids.txt"
  KIRC: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/TCGA_KIRC_patientids.txt"
  LGG: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/TCGA_LGG_patientids.txt"
genomics_file:
  HNSCC:
    HALLMARK: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/HNSCC/HNSCC_HALLMARK_features_filtered.csv"
    KEGG: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/HNSCC/HNSCC_KEGG_features_filtered.csv"
    REACTOME: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/HNSCC/HNSCC_REACTOME_features_filtered.csv"
    BIOCARTA: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/HNSCC/HNSCC_BIOCARTA_features_filtered.csv"
  PDA:
    HALLMARK: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/PDA/PDA_HALLMARK_features_filtered.csv"
    KEGG: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/PDA/PDA_KEGG_features_filtered.csv"
    REACTOME: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/PDA/PDA_REACTOME_features_filtered.csv"
    BIOCARTA: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/PDA/PDA_BIOCARTA_features_filtered.csv"
  CCRCC:
    HALLMARK: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/CCRCC/CCRCC_HALLMARK_features_filtered.csv"
    KEGG: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/CCRCC/CCRCC_KEGG_features_filtered.csv"
    REACTOME: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/CCRCC/CCRCC_REACTOME_features_filtered.csv"
    BIOCARTA: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/CCRCC/CCRCC_BIOCARTA_features_filtered.csv"
  BRCA:
    HALLMARK: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/BRCA/BRCA_HALLMARK_features_filtered.csv"
    KEGG: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/BRCA/BRCA_KEGG_features_filtered.csv"
    REACTOME: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/BRCA/BRCA_REACTOME_features_filtered.csv"
    BIOCARTA: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/BRCA/BRCA_BIOCARTA_features_filtered.csv"
  KIRC:
    HALLMARK: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/KIRC/KIRC_HALLMARK_features_filtered.csv"
    KEGG: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/KIRC/KIRC_KEGG_features_filtered.csv"
    REACTOME: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/KIRC/KIRC_REACTOME_features_filtered.csv"
    BIOCARTA: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/KIRC/KIRC_BIOCARTA_features_filtered.csv"
  LGG:
    HALLMARK: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/LGG/LGG_HALLMARK_features_filtered.csv"
    KEGG: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/LGG/LGG_KEGG_features_filtered.csv"
    REACTOME: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/LGG/LGG_REACTOME_features_filtered.csv"
    BIOCARTA: "/cluster/projects/bhklab/procdata/Radiogenomics/outputs/correlations/LGG/LGG_BIOCARTA_features_filtered.csv"


output_dir: 
  BRCA: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/PANCAN/BRCA/"
  LGG: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/PANCAN/LGG/"
  KIRC: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/PANCAN/KIRC/"
  CCRCC: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/PANCAN/CCRCC/"
  HNSCC: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/PANCAN/HNSCC/"
  PDA: "/cluster/projects/bhklab/procdata/Radiogenomics/clinical/PANCAN/PDA/"